# Generated by Django 5.0.6 on 2024-08-17 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('costumer_name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Pedido')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.product', verbose_name='Produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
